### ISSUE TITLE
Integrate new `provenance.py` script into operational deployment to tag products with Provenance information

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/registry#141]
## 💡 Description

Follow-on to:

* https://github.com/NASA-PDS/registry-api/pull/193
* https://github.com/NASA-PDS/registry-mgr/pull/63
* and ultimately, https://github.com/NASA-PDS/pds-api/issues/221

Need to setup cron or lambda function or ??? to run on semi-regular cadence (every 45 minutes?) to update the operational indexes with the appropriate `superseded_by` metadata.

**Rationale for 45 minute cadence:**
Per discussion on https://github.com/NASA-PDS/pds-api/issues/221, the script takes ~15 minutes to run on a few million products, so 45 minutes should give us plenty of leeway. Additionally, we can then tell node folks to expect their products to be life through the API ~60 minutes after they tag the products for release using Registry Manager.

**Comment by tloubrieu-jpl** [comment]
Steps to migrate:
1. export schema for each of the discipline nodes
2. create a temporary index and add/remove node specificities
3.  reindex on the temporary index
4. rename index

Useful resources:
https://docs.aws.amazon.com/opensearch-service/latest/developerguide/remote-reindex.html
https://opensearch.org/docs/latest/opensearch/reindex-data/

Alternate preferred approach:
1. create the new provenance field so that it is indexed (to be defined)
2. run provenance to populate the new field
3. the new field should be searchable

**Comment by jordanpadams** [comment]
@jimmie wrapping up documentation today. then heading onto schema updates

**Comment by jordanpadams** [comment]
all sub-tasks completed. demoed at 2/23 sprint review and a couple minor tweaks to be wrapped up today
