### ISSUE TITLE
Design authorization handshake with Cognito, API Gateway, and Lambda for multi-tenancy approach

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/registry#179]
## 💡 Description

Follow similar design paradigm as TEA and Data Upload Manager

**Comment by jordanpadams** [comment]
@jimmie should we re-assign this to someone else?

**Comment by jimmie** [comment]
@jordanpadams - it wouldn't hurt to at least establish a co-conspirator so there's a higher degree of accountability.

**Comment by tloubrieu-jpl** [comment]
@sjoshi-jpl will meet with @ramesh-maddegoda  and @collinss-jpl

**Comment by tloubrieu-jpl** [comment]
@sjoshi-jpl here is the diagram I started durinh the meeting https://lucid.app/lucidchart/952eaf32-e735-42a5-b152-d70768f42a57/edit?view_items=S_bQG-howMYj&invitationId=inv_07cbd095-1c59-41d5-a436-2bf5ffde56b7

The harvest CLI repository is on https://github.com/NASA-PDS/harvest/

@jimmie will see with Susan if we can authenticate/authorize the OpenSearch API with Cognito so that we reuse the same credential for cognito and access to the OpenSearch server.

**Comment by tloubrieu-jpl** [comment]
Durinh the SA meeting today, we have been proposed to use opensearch roles which can provide document level access control, see https://opensearch.org/docs/1.2/security-plugin/access-control/document-level-security/

@sjoshi-jpl will explore this option.

@jimmie do you know if you considered that in the initial analysis ?

**Comment by tloubrieu-jpl** [comment]
During the breakout today the option of using the API gateway proxy with authorizer  and Cognito in front of OpenSearch API would be better eventually because:
- we will not need to whitelist IP addresses
- the user can have a single username and password (SSO)
- we can throttle requests.

For this week, @sjoshi-jpl will work on the internal opensearch user management.

Next week, when @jordanpadams and @jimmie come back we will re-evaluate the 2 options (cognito / opensearch)

**Comment by tloubrieu-jpl** [comment]
registry_lists-refs ?
registry_lists-dd ?
registry_lists ?
registry-refs, we would need to add node property to control role access 
registry-dd, this one only access to EN role
registry, we will use the node property to control role access

**Comment by jordanpadams** [comment]
status: numerous discussions with SA team. started with Lambda Authorizer and API Gateway. pivoted for OpenSearch and came to additional hurdles. looking to design with Cognito in the loop for authorization. a couple approaches identified and discussions ongoing with @jimmie @ramesh-maddegoda @viviant100 and @tloubrieu-jpl

**Comment by jordanpadams** [comment]
status: more discussions with SA team. finalized on using Cognito. to be discussed further at breakout.

**Comment by tloubrieu-jpl** [comment]
@sjoshi-jpl the property to filter the documents on is `ops:Harvest_Info/ops:node_name`

Example of values are `PDS_ENG`

**Comment by tloubrieu-jpl** [comment]
@jimmie is testing the opensearch roles for write access.

**Comment by tloubrieu-jpl** [comment]
@sjoshi-jpl is testing the ingestion of data through the signed urls.

**Comment by tloubrieu-jpl** [comment]
The design for multitenant is validated, using one index per node in the multitenant domain.

@sjoshi-jpl is now defined the step to setup a test environment to test this design (cognito groups, IAM roles... )

A migration plan need to be worked on as well.

**Comment by tloubrieu-jpl** [comment]
Waiting for implementation of Cognito authentication on harvest/registry-mgr

**Comment by jordanpadams** [comment]
@sjoshi-jpl waiting on implementation from register loader tools

**Comment by nutjob4life** [comment]
Awaiting registry-sweeper changes

**Comment by jordanpadams** [comment]
Initial design completed: https://lucid.app/lucidchart/369d51af-a9dc-4084-aff2-581acdb9e034/edit?viewport_loc=-871%2C212%2C2160%2C1145%2Cy8hcWSpBkzWo&invitationId=inv_d2bbd83a-de98-4a09-88d8-1456a673ccae

#### Write
![PDS Registry Service Architecture - Write](https://github.com/NASA-PDS/registry/assets/33492486/718308bb-e677-4f6b-b12b-59dab34e251e)


#### Read
![PDS Registry Service Architecture - Read](https://github.com/NASA-PDS/registry/assets/33492486/07eaa702-ac66-441e-bdae-d6050cbf0004)
