### ISSUE TITLE
Update Terraform scripts to support multi-tenancy

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/registry#188]
## 💡 Description

TBD description of what needs to be updated. May be superseded by https://github.com/NASA-PDS/registry/issues/186

**Comment by jimmie** [comment]
There is really nothing specific in the deployment architecture that's required to support multi-tenancy - just a new rev of the task image to include the code that enables it.

Some logistics of course need to be performed if the move to multi-tenancy is performed in the current JPL AWS environment - namely the removal of remotes from the EN Opensearch domain (which activates the use of CCS in the registry service). I don't see a reason to remove the implementation supporting CCS since there could be cases where it could be usefully leveraged - as long as it is deactivated as above, there is no adverse effect to performance or stability.

**Comment by jimmie** [comment]
As correctly indicated in the description, this is superseded by [registry-185](https://github.com/NASA-PDS/registry/issues/185) so I am going to close this one. Feel free to re-open if any of my comments/assumptions made in the previous comment are invalid or questionable.
