### ISSUE TITLE
Secret detection is broken on branch titan_treks_utility_script

### ISSUE THREAD

**Issue by mattanikiej** [NASA-PDS/registry#292]
### Checked for duplicates

No - I haven't checked

### 🐛 Describe the bug

Fails to install plugins and public emails are flagged as secrets.

### 🕵️ Expected behavior

detect-secrets has plugins that should prevent this

### 📜 To Reproduce

Push changes to the repository

### 🖥 Environment Info

- Version of this software [e.g. vX.Y.Z]
- Operating System: [e.g. MacOSX with Docker Desktop vX.Y]
...

### 🦄 Related requirements

🦄 #xyz

**Comment by nutjob4life** [comment]
@mattanikiej perfect, thanks

**Comment by nutjob4life** [comment]
The issue was that the `.secrets.baseline` referenced two `.pem` files which were not included in the commit (indeed, they're in the `.gitignore`).

But when the workflow runs and compares the results with the baseline, it only sees the _difference_, and assumes _any difference_ is a _new disclosure_. A smarter workflow would only report _new disclosures_, not a reduction in secrets.

**Comment by jordanpadams** [comment]
Install issue identified and PR has been merged. #293
