### ISSUE TITLE
Investigate what the number of property per discipline node was at migration time

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry#332]
### 💡 Description

Knowing that there was a limit of 1000 at the time of the migration , I am wondering if we were able to properly migrate all the products or fields.

**Comment by alexdunnjpl** [comment]
@tloubrieu-jpl that limit is on the mappings, iirc?  If so, it will be (has been) resolved by the reindexing sweeper.

**Comment by alexdunnjpl** [comment]
@tloubrieu-jpl fields exist in indices, not documents.  The documents were migrated (with the index mappings being updated prior to migration), so all the content is there, and I see no possibility of limited mappings affecting the migration of document content.

If you have a specific reason for thinking that something was missed I'm all ears, but based on the available information there is no open question that I can see. 

Any problems associated with field-limits on indices have been resolved by my recent manual runs of the reindexer sweepers, unless the limits were removed prior to their execution (~10 days since the earliest, if I recall correctly).

**Comment by alexdunnjpl** [comment]
Recommend closing, pending @tloubrieu-jpl assent

**Comment by tloubrieu-jpl** [comment]
Thanks @alexdunnjpl
